name: CI

on:
  push:
    branches:
      - feature/home_work_35_2 # Укажите Вашу основную ветку

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          docker-compose exec web poetry run python manage.py test  # Укажите команду для запуска тестов

      - name: Stop and remove Docker containers
        run: |
          docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key root@85.92.111.109 "cd /path/to/your/app && git pull && docker-compose up --build -d && sudo systemctl restart your_service"