name: Deploy

on:
  push:
    branches:
      - feature/home_work_35_2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: '1.6.0'
        virtualenvs-create: false
        install: true

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run migrations
      run: poetry run python manage.py migrate

    - name: Run tests
      run: poetry run python manage.py test --parallel

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/new_project_directory/-Django-REST-Framework
          git pull origin ${{ github.ref }}
          sudo systemctl restart gunicorn